services:
  - type: web
    name: corba-pdf-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
