module pdfservice {

    exception PDFException { string message; };

    interface PDFOperations {
        sequence<octet> mergePDFs(in sequence<sequence<octet>> pdfFiles) raises (PDFException);
        sequence<octet> splitPDF(in sequence<octet> pdfFile, in long startPage, in long endPage) raises (PDFException);
        sequence<octet> extractPages(in sequence<octet> pdfFile, in sequence<long> pageNumbers) raises (PDFException);
        sequence<octet> deletePages(in sequence<octet> pdfFile, in sequence<long> pageNumbers) raises (PDFException);
        sequence<octet> addPassword(in sequence<octet> pdfFile, in string userPassword, in string ownerPassword) raises (PDFException);
        sequence<octet> convertToImages(in sequence<octet> pdfFile, in float dpi) raises (PDFException);
        string extractText(in sequence<octet> pdfFile) raises (PDFException);
        sequence<octet> createPDF(in string title, in string content, in string author) raises (PDFException);
        long getPageCount(in sequence<octet> pdfFile) raises (PDFException);
        string ping();
    };
};
