# JacORB Client Configuration
jacorb.connection.client.pending_reply_timeout=30000
jacorb.retries=5
jacorb.retry_interval=1000
jacorb.log.default.verbosity=1
ORBInitRef.NameService=corbaloc::localhost:1050/NameService
